// Code generated by command: go run main.go -out ../galois_amd64.s -pkg=galois. DO NOT EDIT.

#include "textflag.h"

// func _mulVect_16(lohi *[2][16]byte, in []byte, out []byte)
// Requires: AVX
TEXT ·_mulVect_16(SB), NOSPLIT, $0-56
	MOVQ    lohi+0(FP), AX
	MOVQ    in_base+8(FP), CX
	MOVQ    in_len+16(FP), DX
	MOVQ    out_base+32(FP), BX
	MOVQ    CX, SI
	ADDQ    DX, SI
	VMOVDQU (AX), X0
	VMOVDQU 16(AX), X1
	VMOVDQU ·lomask+0(SB), X2
	PCALIGN $0x10

mulVect_start:
	ADDQ    $0x10, CX
	CMPQ    CX, SI
	JA      mulVect_end
	VMOVDQU -16(CX), X3
	VPSRLQ  $0x04, X3, X4
	VPAND   X2, X3, X3
	VPAND   X2, X4, X4
	VPSHUFB X3, X0, X3
	VPSHUFB X4, X1, X4
	VPXOR   X3, X4, X3
	VMOVDQU X3, (BX)
	ADDQ    $0x10, BX
	JMP     mulVect_start

mulVect_end:
	MOVQ    in_base+8(FP), AX
	MOVQ    out_base+32(FP), CX
	ADDQ    DX, AX
	ADDQ    DX, CX
	VMOVDQU -16(AX), X3
	VPSRLQ  $0x04, X3, X4
	VPAND   X2, X3, X3
	VPAND   X2, X4, X4
	VPSHUFB X3, X0, X3
	VPSHUFB X4, X1, X4
	VPXOR   X3, X4, X3
	VMOVDQU X3, -16(CX)
	RET

// func _mulXorVect_16(lohi *[2][16]byte, in []byte, out []byte)
// Requires: AVX
TEXT ·_mulXorVect_16(SB), NOSPLIT, $0-56
	MOVQ    lohi+0(FP), AX
	MOVQ    in_base+8(FP), CX
	MOVQ    in_len+16(FP), DX
	MOVQ    out_base+32(FP), BX
	MOVQ    CX, SI
	ADDQ    DX, SI
	VMOVDQU (AX), X0
	VMOVDQU 16(AX), X1
	VMOVDQU ·lomask+0(SB), X2
	VMOVDQU -16(BX)(DX*1), X5
	PCALIGN $0x10

mulXorVect_start:
	ADDQ    $0x10, CX
	CMPQ    CX, SI
	JA      mulXorVect_end
	VMOVDQU -16(CX), X3
	VPSRLQ  $0x04, X3, X4
	VPAND   X2, X3, X3
	VPAND   X2, X4, X4
	VPSHUFB X3, X0, X3
	VPSHUFB X4, X1, X4
	VPXOR   X3, X4, X3
	VPXOR   (BX), X3, X3
	VMOVDQU X3, (BX)
	ADDQ    $0x10, BX
	JMP     mulXorVect_start

mulXorVect_end:
	MOVQ    in_base+8(FP), AX
	MOVQ    out_base+32(FP), CX
	ADDQ    DX, AX
	ADDQ    DX, CX
	VMOVDQU -16(AX), X3
	VPSRLQ  $0x04, X3, X4
	VPAND   X2, X3, X3
	VPAND   X2, X4, X4
	VPSHUFB X3, X0, X3
	VPSHUFB X4, X1, X4
	VPXOR   X3, X4, X3
	VPXOR   X5, X3, X3
	VMOVDQU X3, -16(CX)
	RET

// func _xorVect_16(in []byte, out []byte)
// Requires: AVX
TEXT ·_xorVect_16(SB), NOSPLIT, $0-48
	MOVQ    in_base+0(FP), AX
	MOVQ    in_len+8(FP), CX
	MOVQ    out_base+24(FP), DX
	MOVQ    AX, BX
	ADDQ    CX, BX
	VMOVDQU -16(DX)(CX*1), X1
	PCALIGN $0x10

xorVect_start:
	ADDQ    $0x10, AX
	CMPQ    AX, BX
	JA      xorVect_end
	VMOVDQU -16(AX), X0
	VPXOR   (DX), X0, X0
	VMOVDQU X0, (DX)
	ADDQ    $0x10, DX
	JMP     xorVect_start

xorVect_end:
	MOVQ    in_base+0(FP), AX
	MOVQ    out_base+24(FP), DX
	ADDQ    CX, AX
	ADDQ    CX, DX
	VMOVDQU -16(AX), X0
	VPXOR   X1, X0, X0
	VMOVDQU X0, -16(DX)
	RET
