package galois

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"math/rand"
	"os"
	"slices"
	"strconv"
	"strings"
	"testing"
	"time"
)

func Test_generate(t *testing.T) {
	if !slices.Contains(os.Args, "generate") {
		return
	}
	mul := newMul()
	lohi := newLohi(mul)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by \"go test %s\"; DO NOT EDIT.\n\n", strings.Join(os.Args[1:], " "))
	file := &ast.File{
		Name:  ast.NewIdent("galois"),
		Decls: []ast.Decl{lohiTableDecl(lohi), mulTableDecl(mul)},
	}
	if err := format.Node(&b, token.NewFileSet(), file); err != nil {
		t.Fatal(err)
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile("table_gen.go", src, 0o644); err != nil {
		t.Fatal(err)
	}
}
func newMul() *[256][256]byte {
	var t [256][256]byte
	for a := range t {
		for b := range t[a] {
			if a == 0 || b == 0 {
				t[a][b] = 0
				continue
			}
			logA := int(logTable[a])
			logB := int(logTable[b])
			logSum := logA + logB
			for logSum >= 255 {
				logSum -= 255
			}
			t[a][b] = expTable[logSum]
		}
	}
	return &t
}
func newLohi(mul *[256][256]byte) *[256]lohi {
	var t [256]lohi
	for i := 0; i < 256; i++ {
		for j := 0; j < 256; j++ {
			var v byte
			if !(i == 0 || j == 0) {
				v = mul[i][j]
			}

			if (j & 0x0f) == j {
				t[i].lo[j] = v
			}
			if (j & 0xf0) == j {
				t[i].hi[j>>4] = v
			}
		}
	}
	return &t
}
func mulTableDecl(mul *[256][256]byte) ast.Decl {
	rows := make([]ast.Expr, 0, 256)
	for a := 0; a < 256; a++ {
		elts := make([]ast.Expr, 0, 256)
		for j := 0; j < 256; j++ {
			elts = append(elts, &ast.BasicLit{Kind: token.INT, Value: strconv.Itoa(int(mul[a][j]))})
		}
		rows = append(rows, &ast.CompositeLit{Elts: elts})
	}
	return &ast.GenDecl{
		Tok: token.VAR,
		Doc: &ast.CommentGroup{List: []*ast.Comment{{Text: "// for vect calc, 64KB"}}},
		Specs: []ast.Spec{
			&ast.ValueSpec{
				Names: []*ast.Ident{ast.NewIdent("mulTable")},
				Values: []ast.Expr{&ast.CompositeLit{
					Type: &ast.ArrayType{Len: ast.NewIdent("256"), Elt: &ast.ArrayType{Len: ast.NewIdent("256"), Elt: ast.NewIdent("byte")}},
					Elts: rows,
				}},
			},
		},
	}
}

func lohiTableDecl(lohi *[256]lohi) ast.Decl {
	rows := make([]ast.Expr, 0, 256)
	for i := 0; i < 256; i++ {
		lo := make([]ast.Expr, 0, 16)
		for j := 0; j < 16; j++ {
			lo = append(lo, &ast.BasicLit{Kind: token.INT, Value: strconv.Itoa(int(lohi[i].lo[j]))})
		}
		hi := make([]ast.Expr, 0, 16)
		for j := 0; j < 16; j++ {
			hi = append(hi, &ast.BasicLit{Kind: token.INT, Value: strconv.Itoa(int(lohi[i].hi[j]))})
		}
		rows = append(rows, &ast.CompositeLit{
			Elts: []ast.Expr{
				&ast.KeyValueExpr{
					Key:   ast.NewIdent("lo"),
					Value: &ast.CompositeLit{Type: &ast.ArrayType{Len: ast.NewIdent("16"), Elt: ast.NewIdent("byte")}, Elts: lo},
				},
				&ast.KeyValueExpr{
					Key:   ast.NewIdent("hi"),
					Value: &ast.CompositeLit{Type: &ast.ArrayType{Len: ast.NewIdent("16"), Elt: ast.NewIdent("byte")}, Elts: hi},
				},
			},
		})
	}
	return &ast.GenDecl{
		Tok: token.VAR,
		Doc: &ast.CommentGroup{List: []*ast.Comment{{Text: "// for scalar calc, 8KB"}}},
		Specs: []ast.Spec{
			&ast.ValueSpec{
				Names: []*ast.Ident{ast.NewIdent("lohiTable")},
				Values: []ast.Expr{&ast.CompositeLit{
					Type: &ast.ArrayType{Len: ast.NewIdent("256"), Elt: ast.NewIdent("lohi")},
					Elts: rows,
				}},
			},
		},
	}
}

func Test_new_Table(t *testing.T) {
	{
		ta := &mulTable

		var b = make([]byte, 0, 0xffff)
		for _, e := range ta {
			b = append(b, e[:]...)
		}

		exp := [32]byte{20, 161, 231, 231, 124, 168, 163, 11, 91, 181, 62, 99, 16, 116, 140, 224, 73, 142, 185, 224, 74, 183, 138, 68, 219, 239, 182, 235, 250, 200, 168, 75}
		act := sha256.Sum256(b)
		if exp != act {
			t.Fatalf("sha256 mismatch")
		}
	}
	{
		lh := &lohiTable

		var b = make([]byte, 0, 8192)
		for _, e := range lh {
			b = append(b, e.lo[:]...)
			b = append(b, e.hi[:]...)
		}

		exp := [32]byte{184, 32, 66, 66, 250, 216, 134, 44, 232, 30, 221, 162, 147, 133, 189, 197, 92, 76, 35, 112, 253, 64, 163, 61, 96, 187, 148, 151, 230, 165, 47, 246}
		act := sha256.Sum256(b)
		if exp != act {
			t.Fatalf("sha256 mismatch")
		}
	}
}

func Test_mul_lowhigh_cross_verify(t *testing.T) {
	// galois mul
	//
	// for i, e := range in {
	// 	  out[i] = mul[e]
	// 	  out[i] = lo[e&0x0f] ^ hi[e>>4]
	// }

	seed := time.Now().UnixNano()
	t.Logf("seed: %d", seed)
	r := rand.New(rand.NewSource(seed))

	for range 0xff {
		c := byte(r.Int31n(0xff))
		var in = make([]byte, r.Int31n(1536)+1)
		r.Read(in)

		var out1 = make([]byte, len(in))
		mul := mulTable[c]
		for i, e := range in {
			out1[i] = mul[e]
		}

		var out2 = make([]byte, len(in))
		lohimk := lohiTable[c]
		for i, e := range in {
			out2[i] = lohimk.lo[e&0x0f] ^ lohimk.hi[e>>4]
		}

		if !bytes.Equal(out1, out2) {
			t.Fatalf("mul mismatch")
		}
	}
}
