name: test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      GOEXPERIMENT: simd
      GOARCH: ${{ matrix.goarch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux/amd64
            os: ubuntu-latest
            goarch: amd64
          - name: windows/amd64
            os: windows-latest
            goarch: amd64
          - name: macos/arm64
            os: macos-latest
            goarch: arm64
          - name: linux/386
            os: ubuntu-latest
            goarch: "386"
    defaults:
      run:
        shell: bash -eo pipefail {0}
    steps:
      - uses: actions/checkout@v6
        with:
          path: merge
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.base.sha || github.event.before }}
          path: master
      - uses: actions/setup-go@v6
        with:
          go-version-file: merge/go.mod
          cache: true
          cache-dependency-path: |
            merge/go.sum
            merge/.github/ci/go.sum

      - name: format
        working-directory: merge
        run: |
          go mod tidy
          go generate ./...
          go vet ./...
          go vet -tags debug ./...
          go fmt ./...

      - name: ci test
        working-directory: merge/.github/ci
        run: go run . test --master ../../../master --merge ../.. --name "${{ matrix.name }}"

      - run: git diff --exit-code
        working-directory: merge

  bench:
    runs-on: ${{ matrix.os }}
    env:
      GOEXPERIMENT: simd
      GOARCH: ${{ matrix.goarch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: amd64
            os: ubuntu-latest
            goarch: amd64
          - name: arm64
            os: macos-latest
            goarch: arm64
    defaults:
      run:
        shell: bash -eo pipefail {0}
    steps:
      - uses: actions/checkout@v6
        with:
          path: merge
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.base.sha || github.event.before }}
          path: master
      - uses: actions/setup-go@v6
        with:
          go-version-file: merge/go.mod
          cache: true
          cache-dependency-path: |
            merge/go.sum
            merge/.github/ci/go.sum

      - name: ci bench
        working-directory: merge/.github/ci
        run: go run . bench --master ../../../master --merge ../.. --name "${{ matrix.name }}" --max-retry 3

  checks-done:
    needs: [test, bench]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: |
          test "${{ needs.test.result }}" = success
          test "${{ needs.bench.result }}" = success
